//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activity1Client.Activity1ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Activity1ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sumOfDigits", ReplyAction="http://tempuri.org/IService1/sumOfDigitsResponse")]
        int sumOfDigits(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sumOfDigits", ReplyAction="http://tempuri.org/IService1/sumOfDigitsResponse")]
        System.Threading.Tasks.Task<int> sumOfDigitsAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numVowels", ReplyAction="http://tempuri.org/IService1/numVowelsResponse")]
        int numVowels(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numVowels", ReplyAction="http://tempuri.org/IService1/numVowelsResponse")]
        System.Threading.Tasks.Task<int> numVowelsAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Activity1Client.Activity1ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Activity1Client.Activity1ServiceReference.IService1>, Activity1Client.Activity1ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int sumOfDigits(int value) {
            return base.Channel.sumOfDigits(value);
        }
        
        public System.Threading.Tasks.Task<int> sumOfDigitsAsync(int value) {
            return base.Channel.sumOfDigitsAsync(value);
        }
        
        public int numVowels(string str) {
            return base.Channel.numVowels(str);
        }
        
        public System.Threading.Tasks.Task<int> numVowelsAsync(string str) {
            return base.Channel.numVowelsAsync(str);
        }
    }
}
